### ISSUE TITLE
Not iterating frames

### ISSUE THREAD

**Issue by SamambaMan** [stranger80/GraviRayTraceSharp#1]
Hi, 

I'v run the raytracer with the DefaultControlFile.txt provided.
Here folows it's contents:
GraviRayTraceSharp.Scene.DefaultPathSceneGenerator, GraviRayTraceSharp
.
640 480
1
High
10 1
20 1
30 1
40 1
50 1
60 1
70 1
80 1
90 1
100 1
110 1
120 1
130 1
140 1
150 1
160 1
170 1
180 1
190 1
200 1
210 1

The method CommitFrameNo isn't writing the tokenChar into the file, so the raytracer always try to render the "10" frame. 

Downloaded, built in release, just plain github code.

Thanks for the amazing code!

**Comment by stranger80** [comment]
Hi,

The published code works properly on at least 20 different machines. What platform are you on? We are all on Windows 7. The logic that you mention works using a two-way file stream (ie. file stream which is used both to read and write, with stream position changing) - is it possible that stream.Seek() works differently for you? Do any changes get written back to control file? Do you see a '2' appearing anywhere once processing starts on the first frame?

**Comment by SamambaMan** [comment]
Hi!

Thanks for your answer.

I'm running on Windows 7, under Visual Studio 2012.
It keeps in the first frame, and yes, there is a "2" in the seccond frame, follows:
GraviRayTraceSharp.Scene.DefaultPathSceneGenerator, GraviRayTraceSharp
.
640 480
1
High
10 1
20 2
30 1
40 1
50 1
60 1
70 1
80 1
90 1
100 1
110 1
120 1
130 1
140 1
150 1
160 1
170 1
180 1
190 1
200 1
210 1

It actualy writes the first frame in the disk , but keeps on the first frame forever.
Any idea? Is there something that I could do? 

Thanks in advance!

**Comment by stranger80** [comment]
Have you downloaded the code via 'Download ZIP' or using GitHub client?

**Comment by stranger80** [comment]
Committed a fix to control file processor, to handle different <end-of-line> encodings.
